language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
env:
  - DJANGO_VERSION=1.4.20
  - DJANGO_VERSION=1.5.12
  - DJANGO_VERSION=1.6.11
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8
install:
  - pip install -r test-requirements.txt
  - pip install -q Django==$DJANGO_VERSION
script: "coverage run --source=collectfast ./runtests.py"
after_success:
  coveralls
matrix:
  exclude:
    - python: "3.2"
      env: DJANGO_VERSION=1.4.20
    - python: "3.3"
      env: DJANGO_VERSION=1.4.20
